### ISSUE TITLE
Optimize computation of forcings.

### ISSUE THREAD

**Issue by dietervdb-meteo** [ecmwf/anemoi-inference#50]
### Is your feature request related to a problem? Please describe.

When using the branch feature/refactor it appears that forcings are computed one time too many. E.g. if one performs only a 6h forecast forcings are computed but they are not needed. 

### Describe the solution you'd like

When performing a forecast N steps in the future, forcings should be computed only N-1 times.

### Organisation

RMI

**Comment by frazane** [comment]
Can be closed (solved by #71)

**Comment by dietervdb-meteo** [comment]
Great!
